Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/routes/cust.py
from flask import Blueprint, render_template, request, redirect, session, url_for
from flask_login import login_required, logout_user
import ibm_db
from .views import conn, pass_regex, mail
import uuid
from datetime import date, datetime
import re
import hashlib


QUERY_STATUS_OPEN = "OPEN"
QUERY_STATUS_ASSIGNED_AGENT = "AGENT ASSIGNED"
QUERY_STATUS_CLOSE = "CLOSE"

cust = Blueprint("customer", __name__)

@cust.route('/customer/')
@login_required
def profile():
    '''
        Custome can see his/her profile card
    '''
    from .views import customer
        
    if hasattr(customer, 'uuid'):
        return render_template('cust profile.html', customer = customer, id = 0)

    else:
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/new', methods = ['GET', 'POST'])
@login_required
def new():
    '''
        Customer can create a new ticket 
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        if request.method == 'POST':
            # collecting the query entered by the customer in the textarea
            query = request.form.get('query-box')

            msg = ""
            to_show = False

            if(len(query) == 0):
                msg = "Query cannot be empty!"
                to_show = True

            else:
                # updating the query in the database
                update_query = '''
                    INSERT INTO tickets 
                        (ticket_id, raised_by, raised_on, issue, query_status)
                    VALUES 
                        (?, ?, ?, ?, ?)
                '''

                try:
                    stmt = ibm_db.prepare(conn, update_query)

                    # creating a uuid for the ticket_id
                    ticket_id = str(uuid.uuid4())
                    raised_by = customer.uuid
                    raied_on = datetime.now()

                    ibm_db.bind_param(stmt, 1, ticket_id)
                    ibm_db.bind_param(stmt, 2, raised_by)
                    ibm_db.bind_param(stmt, 3, raied_on)
                    ibm_db.bind_param(stmt, 4, query)
                    ibm_db.bind_param(stmt, 5, QUERY_STATUS_OPEN)

                    ibm_db.execute(stmt)

                    msg = "Ticket created!"
                    to_show = True

                    send_email = session['EMAIL']

                    # sending the acknowledgement mail to the customer
                    mail.sendEmail(
                        f'Customer Care Registry', 
                        f'''Welcome {session['FIRST_NAME']}! <br/>
                            You have created a new ticket! <br/>
                            Ticket ID : <strong>{ticket_id}</strong> <br/>
                            Query : <strong>{query}</strong> <br/> <br/>
                            <br/>
                            An agent will be assigned to you very soon!! <br/>
                            Stay Tuned...''',
                        [f'{send_email}']
                    )

                except:
                    msg = "Something went wrong!"
                    to_show = True

            return render_template('cust new ticket.html', id = 1, to_show = to_show, message = msg)

        return render_template('cust new ticket.html', id = 1)

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))

@cust.route('/customer/tickets')
@login_required
def tickets():
    '''
        Fetching all the tickets raised by the customer
    '''
    from .views import customer

    if(hasattr(customer, 'uuid')):
        fetch_query = '''
            SELECT  
                tickets.ticket_id,
                tickets.raised_on,
                tickets.query_status,
                agent.first_name, 
                tickets.issue,
                tickets.raised_by
            FROM
                tickets
            LEFT JOIN 
                agent ON agent.agent_id = tickets.assigned_to 
            ORDER BY tickets.raised_on DESC
        '''

        from .views import customer
        raised_by = customer.uuid

        try:
            stmt = ibm_db.prepare(conn, fetch_query)
            ibm_db.execute(stmt)

            tickets = ibm_db.fetch_assoc(stmt)
            tickets_list = []

            if tickets:
                # means, the customer has raised some tickets before
                while tickets != False:
                    if raised_by == tickets['RAISED_BY']:
                        temp = []

                        temp.append(tickets['TICKET_ID'])
                        temp.append(str(tickets['RAISED_ON'])[0:10])
                        temp.append(tickets['QUERY_STATUS'])
                        temp.append(tickets['ISSUE'])
                        temp.append(tickets['FIRST_NAME'])

                        tickets_list.append(temp)                       

                    tickets = ibm_db.fetch_assoc(stmt)

                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = True,
                    tickets = tickets_list,
                    msg = "These are your tickets"
                )

            else:
                # means, the customer is yet to raise a ticket
                return render_template(
                    'cust tickets.html',
                    id = 2,
                    tickets_to_show = False,
                    msg = "You are yet to rise a ticket"
                )

        except:
            # something fishy happened while loading the customer's tickets
            return render_template(
                'cust tickets.html',
                id = 2,
                to_show = True,
                message = "Something went wrong! Please Try Again"
            )

    else:
        # logging out
        return redirect(url_for('blue_print.logout'))
    
@cust.route('/customer/change', methods = ['GET', 'POST'])
@login_required
def change():
    '''
        Changing the password of the customer
    '''
    from .views import customer
    
    if hasattr(customer, 'first_name'):
        if request.method == 'POST':
            # getting the passwords entered by the customer
            password = request.form.get('password')
            new1 = request.form.get('new-pass-1')
            new2 = request.form.get('new-pass-2')

            msg = ""
            to_show = False

            # validating the passwords entered by the ucer
            if((len(password) or len(new1) or len(new2)) < 8):
                password = new1 = new2 = ""
                msg = "Passwords must be atleast 8 characters long!!" 
                to_show = True     

            elif new1 != new2:
                password = new1 = new2 = ""
                msg = "Passwords do not match" 
                to_show = True

            elif password == new1:
                password = new1 = new2 = ""
                msg = "Old and New passwords cannot be same" 
                to_show = True

            elif (not (re.fullmatch(pass_regex, new1))):
                password = new1 = new2 = ""
                msg = "Enter a valid password"
                to_show = True

            # by here the passwords are evaluated
            if not to_show:
                # updating the password of the customer
                # only if, the existing password of the user is valid
                # checking that if is true the database

                # query tp get the existing encrypted password of the customer
                get_password_sha = '''
                    SELECT passcode FROM customer WHERE cust_id = ?
                '''

                try:
                    stmt = ibm_db.prepare(conn, get_password_sha)
                    ibm_db.bind_param(stmt, 1, customer.uuid)
                    ibm_db.execute(stmt)

                    existing = ibm_db.fetch_assoc(stmt)['PASSCODE']

                    # checking 
                        # if the existing encrypted password is equal to
                        # the encrypted one of the one
                    # that is enetered by the customer
                    
                    # passwords match
                    if (existing == str(hashlib.sha256(password.encode()).hexdigest())):
                        # updating the password of the customer

                        # query to update the password
                        update_password_query = '''
                            UPDATE customer SET passcode = ? WHERE cust_id = ?
                        '''

                        # enrcypting the new password entered by the user
                        enc = str(hashlib.sha256(new1.encode()).hexdigest())

                        change = ibm_db.prepare(conn, update_password_query)
                        ibm_db.bind_param(change, 1, enc)
                        ibm_db.bind_param(change, 2, customer.uuid)

                        ibm_db.execute(change)

                        send_mail = session['EMAIL']

                        # sending the acknowledgement mail to the customer
                        mail.sendEmail(
                            f'Customer Care Registry', 
                            f'''Welcome {session['FIRST_NAME']}! <br/>
                                It seems you have changed your password! <br/>
                                If it is not you, kindly report to us <br/>
                                Thank you!!
                            ''',
                            [f'{send_mail}']
                        )

                        # password is changed
                        # now logging out the customer and re-directing to login page
                        logout_user()
                        session.clear()
                        
                        return render_template(
                            'login.html',
                            email = customer.email,

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/admin agents.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All Agents
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>All Agents</h1>

        <div class="new-t-div">
            {% if agents_to_show %}
                <p>{{ msg }}</p>
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">AGENT ID</th>
                        <th class="agents-table-heading">JOINED DATE</th>
                        <th class="agents-table-heading">FIRST NAME</th>
                        <th class="agents-table-heading">LAST NAME</th>
                        <th class="agents-table-heading">EMAIL</th>
                    </tr>
                    {% for agent in agents %}
                        <tr>
                            <td class="agents-table-element">{{ agent[0][0:5] }}</td>
                            <td class="agents-table-element">{{ agent[1] }}</td>
                            <td class="agents-table-element">{{ agent[2] }}</td>
                            <td class="agents-table-element">{{ agent[3] }}</td>
                            <td class="agents-table-element">{{ agent[4] }}</td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/admin dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div" onload="highlight()">
        <ul id="dash-parent-list">
            <li> 
                <a href="{{ url_for('admin.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.agents') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Agents</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.accept') }}">
                    <div class="link-items">
                        <div><i class="fa fa-question" aria-hidden="true"></i></div>
                        <h3>Requests</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('admin.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
        }
    </script>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/admin support.html
{% extends 'admin dashboard.html' %}

{% block title %}
    Feedbacks
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Feedbacks received!</h1>

        <div class="new-t-div">
            {% if true %}
                <p>{{ msg }}</p>
                <div class="feed-div">
                    {% for feedback in feedbacks %}
                        <div class="feedback-column">
                            <p class="feedback-text">"{{ feedback[3] }}"</p>
                            <p class="feedback-by">By {{ feedback[2] }} ({{ feedback[1] }})</p>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}            
        </div>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/admin tickets.html
{% extends 'admin dashboard.html' %}

{% block title %}
    All tickets
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Unassigned Tickets</h1>

        <div class="new-t-div">
            {% if tickets_to_show %}
                <p>{{ msg }}</p>
                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">TICKET ID</th>
                        <th class="agents-table-heading">DATE</th>
                        <th class="agents-table-heading">CUSTOMER</th>
                        <th class="agents-table-heading">QUERY</th>
                        <th class="agents-table-heading">ASSIGN</th>
                    </tr>
                    {% for ticket in tickets %}
                        <tr>
                            <td class="agents-table-element">{{ ticket[0][0:5] }}</td>
                            <td class="agents-table-element">{{ ticket[1] }}</td>
                            <td class="agents-table-element">{{ ticket[2] }}</td>
                            <td class="agents-table-element">
                                <button onclick="showTicket('{{ ticket[3] }}')" class="view-query">View</button>
                            </td>
                            <td class="agents-table-element">
                                <select class="agent-select" id="for-customer" onclick="agentSelected()" > 
                                    <option class="agent-option" selected value="Choose">Choose</option>
                                    {% for agent in agents %}
                                        <option class="agent-option" value="{{ agent[1] }} {{ ticket[0] }} {{ ticket[4] }}">{{ agent[0] }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>

    <script>
        function showTicket(ticket){
            alert(ticket)
        }

        function agentSelected(){
            var x = document.getElementById('for-customer').value;
            console.log(x)

            if (x != "Choose"){
                var decision = confirm("Are you sure you want to assign this agent?")
                const temp = x.split(" ")
                console.log(temp)

                if(decision){
                    url = '/admin/update/' + temp[0] + '/' + temp[1] + '/' + temp[2] + '/'
                    
                    fetch(url, {

                    }).then((_res) => {
                        window.location.href = "/admin/tickets"
                    })
                }
            }
        }
    </script>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/agent about.html
{% extends 'agent dashboard.html' %}

{% block title %}
    About
{% endblock %}

{% block right %}
<div class="profile-div">
    <h1>About</h1>

    <div class="new-t-div">
        <p>You might as well know all these as an agent</p>

        <div class="about-div">
            <ul>
                <li>Customers create ticket to clarify their queries.</li>
                <li>Admin assigns some of the tickets to you.</li>
                <li>Once assigned to you, you chat with the customer.</li>
                <li>During the same, you can answer to the customer.</li>
                <li>Customer closes the ticket once satisfied.</li>
            </ul>

            <a href="{{ url_for('agent.assigned') }}" class="submit-btn new-bol">Tickets assigned</a>
        </div>
    </div>
</div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/agent change.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Change Password</h1>

        <div class="new-t-div">
            <p>Feeling your old password is not good enough?</p>
            
            <div class="change-password-div">
                <form action="{{ url_for('agent.change') }}" method="POST">
                    <label>Password</label>
                    <input name="password" class="change-pass-in" id="password-input" type="password" placeholder="Current Password" />

                    <label>New Password</label>
                    <input name="new-pass-1" class="change-pass-in" id="password-input1" type="password" placeholder="New Password" />

                    <label>Confirm Password</label>
                    <input name="new-pass-2" class="change-pass-in" id="password-input2" type="password" placeholder="New Password" /> <br/>
                    
                    <p>Use 8 or more characters with a mix of just letters and numbers</p>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>
                    
                    <button style="width: 150px;" class="submit-btn">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/agent profile.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Welcome {{ agent.first_name }}!
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <th colspan="2" class="prof-table-th">Profile</th>
            </tr>
            <tr>
                <td>First Name</td>
                <td>{{ agent.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ agent.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Agent</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ agent.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ agent.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/agent tickets.html
{% extends 'agent dashboard.html' %}

{% block title %}
    Tickets Assigned
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Tickets assigned to you!</h1>
        
        <div class="new-t-div">
            {% if tickets_to_show %}
                <p>{{ msg }}</p>
                <table class=agents-table>
                    <tr>
                        <th class="agents-table-heading">TICKET ID</th>
                        <th class="agents-table-heading">DATE</th>
                        <th class="agents-table-heading">RAISED <br/> BY</th>
                        <th class="agents-table-heading">STATUS</th>
                        <th class="agents-table-heading">QUERY</th>
                        <th class="agents-table-heading">ADDRESS <br/> COLUMN</th>
                    </tr>
                    {% for ticket in tickets %}
                        <tr>
                            <td class="agents-table-element">{{ ticket[0][0:5] }}</td>
                            <td class="agents-table-element">{{ ticket[1] }}</td>
                            <td class="agents-table-element">{{ ticket[2] }}</td>
                            <td class="agents-table-element">
                                {% if ticket[3] == "OPEN" %}
                                    <div class="open-ticket">
                                        {{ ticket[3] }}
                                    </div>
                                {% else %}
                                    <div class="open-ticket closed-ticket">
                                        {{ ticket[3] }}
                                    </div>
                                {% endif %}
                            </td>
                            <td class="agents-table-element">
                                <button onclick="showTicket('{{ ticket[4] }}')" class="view-query">View</button>
                            </td>
                            <td class="agents-table-element">
                                {% if ticket[3] == "OPEN" %}
                                    <a href="/chat/{{ ticket[0] }}/ {{ ticket[2] }}/" class="view-query">Chat</a>
                                {% else %}
                                    <a href="/chat/{{ ticket[0] }}/ {{ ticket[2] }}/" class="view-query">Visit</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>

    <script>
        /* Function to show the query of the ticket */
        function showTicket(ticket){
            alert(ticket)
        }
    </script>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/cust change.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Change Password
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Change Password</h1>

        <div class="new-t-div">
            <p>Feeling your old password is not good enough?</p>
            
            <div class="change-password-div">
                <form action="{{ url_for('customer.change') }}" method="POST">
                    <label>Password</label>
                    <input name="password" class="change-pass-in" id="password-input" type="password" placeholder="Current Password" />
    
                    <label>New Password</label>
                    <input name="new-pass-1" class="change-pass-in" id="password-input1" type="password" placeholder="New Password" />
    
                    <label>Confirm Password</label>
                    <input name="new-pass-2" class="change-pass-in" id="password-input2" type="password" placeholder="New Password" /> <br/>
                    
                    <p>Use 8 or more characters with a mix of just letters and numbers</p>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>
                    
                    <button style="width: 150px;" class="submit-btn">Submit</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/cust dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
    <div class="links-left-div">
        <ul  id="dash-parent-list">
            <li>
                <a href="{{ url_for('customer.profile') }}">
                    <div class="link-items">
                        <div><i class="fa fa-user" aria-hidden="true"></i></div>
                        <h3>Profile</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.new') }}">
                    <div class="link-items">
                        <div><i class="fa fa-plus" aria-hidden="true"></i></div>
                        <h3>New ticket</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.tickets') }}">
                    <div class="link-items">
                        <div><i class="fa fa-ticket" aria-hidden="true"></i></div>
                        <h3>Tickets</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.change') }}">
                    <div class="link-items">
                        <div><i class="fa fa-key" aria-hidden="true"></i></div>
                        <h3>Change Password</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.about') }}">
                    <div class="link-items">
                        <div><i class="fa fa-info" aria-hidden="true"></i></div>
                        <h3>About</h3>
                    </div>
                </a>
            </li>
            <li>
                <a href="{{ url_for('customer.support') }}">
                    <div class="link-items">
                        <div><i class="fa fa-comments-o" aria-hidden="true"></i></div>
                        <h3>Feedback</h3>
                    </div>
                </a>
            </li>
        </ul>
    </div>

    <script>
        window.onload = function highlight(){
            id = '{{ id }}'
            var element = document.getElementById('dash-parent-list').children.item(id);
            element.className = "active";
            console.log("function called")
        }
    </script>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/cust new ticket.html
{% extends 'cust dashboard.html' %}

{% block title %}
    New ticket
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Raise a new ticket</h1>
        <div class="new-t-div">
            <p>In case you have any issues, you can raise a new ticket with the detailed
                description of the issue. An agent will be assigned for your ticket. And you will
                receive expert answers
            </p>
            <form method="POST" action="{{ url_for('customer.new') }}">
                <textarea name="query-box" class="ticket-area" maxlength="800" placeholder="Your Query..."></textarea>
                <p>* Please make sure the query is legible</p>
                <button type="submit" id="new-ticket" class="submit-btn" style="width: 200px;">New Ticket</button>
            </form>
        </div>
    </div>
{% endblock %}

Final Deliverables/CUSTOMER CARE REGISTRY/Customer Care Registry/registry/templates/cust profile.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Welcome {{ customer.first_name }}
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Welcome to CCR!</h1>
        <table class="prof-table">
            <tr>
                <th colspan="2" class="prof-table-th">Profile</th>
            </tr>
            <tr>
                <td>First Name</td>
                <td>{{ customer.first_name }}</td>
            </tr>
            <tr>
                <td>Last Name</td>
                <td>{{ customer.last_name }}</td>
            </tr>
            <tr>
                <td>Role</td>
                <td>Customer</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ customer.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ customer.date }}</td>
            </tr>
        </table>
    </div>
{% endblock %}