Project Development Phase/Sprint 2/Customer Care Registry/registry/views.py
from flask import Blueprint, render_template, request, redirect, session, url_for
import hashlib
import re
from flask_login import login_required, login_user, logout_user
import ibm_db
import uuid
from datetime import date
from .model import Customer, Agent, Admin

views = Blueprint("blue_print", __name__)
email_regex = r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"
pass_regex = r"^[A-Za-z0-9_-]*$"

customer = Customer()
agent = Agent()
admin = Admin()

conn = ibm_db.connect('DATABASE=bludb;HOSTNAME=2f3279a5-73d1-4859-88f0-a6c3e6b4b907.c3n41cmd0nqnrk39u98g.databases.appdomain.cloud;PORT=30756;SECURITY=SSL;SSLServerCertificate=DigiCertGlobalRootCA.crt;UID=tdn81266;PWD=7LY8okjAouJf3LoO', '', '')

@views.route('/logout')
@login_required
def logout():
    session.pop('LOGGED_IN_AS')
    logout_user()

    return redirect(url_for('blue_print.login'))

@views.route('/', methods = ['GET', 'POST'])
def login():
    # if method is POST
    if request.method == 'POST':
        # getting the data entered by the user 
        email = request.form.get('email')
        password = request.form.get('password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs entered by the user
        if(not (re.fullmatch(email_regex, email))):
            msg = "Enter a valid email"
            to_show = True

        elif (len(password) < 8):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        # Admin login
        if email == "admin.ccr@gmail.com":
            if password == "admin.ccr@2022":
                # initialising admin object
                admin.set(email, password)

                session.permanent = False
                session['LOGGED_IN_AS'] = "ADMIN"                            
                login_user(admin, remember=True)
                
                return redirect(url_for('admin.tickets'))

            else:
                to_show = True
                password = ""
                msg = "Invalid password!"

        # Customer or Agent
        else:
            if to_show:
                # there is something fishy with the user's inputs
                password = ""

            elif (not to_show):
                # the user's inputs are valid
                # checking if the login credentials are valid
                if role == "Customer":
                    # checking if the entry of the mail entered is present in the database
                    mail_check_query = "SELECT * FROM customer WHERE email = ?"
                    stmt = ibm_db.prepare(conn, mail_check_query)
                    ibm_db.bind_param(stmt, 1, email)
                    ibm_db.execute(stmt)

                    account = ibm_db.fetch_assoc(stmt)

                    if account:
                        # valid customer
                        # i.e, mail is present in the database

                        # checking if the customer entered a valid password now
                        # encrypting the entered password
                        passcode = str(hashlib.sha256(password.encode()).hexdigest())

                        # now checking if the encrypted string is same as that of the one in database
                        if (account['PASSCODE'] == passcode):
                            msg = "Valid Login"
                            to_show = True

                            # creating a customer object
                            customer.set(
                                account['CUST_ID'],
                                account['FIRST_NAME'],
                                account['LAST_NAME'],
                                account['EMAIL'],
                                account['PASSCODE'],
                                account['DATE_JOINED']
                            )

                            session.permanent = False
                            session['LOGGED_IN_AS'] = "CUSTOMER"
                            login_user(customer, remember=True)

                            return redirect(url_for('customer.profile'))

                        else:
                            # customer entered invalid password
                            msg = "Invalid password"
                            password = ""
                            to_show = True

                    else:
                        # invalid customer
                        # i.e, entered mail is not present in the database
                        msg = "User does not exist"
                        email = ""
                        password = ""
                        to_show = True

                else:
                    # user is an Agent
                    # checking if the entry of the mail entered is present in the agent's table
                    mail_check_query = "SELECT * FROM agent WHERE email = ?"
                    stmt = ibm_db.prepare(conn, mail_check_query)
                    ibm_db.bind_param(stmt, 1, email)
                    ibm_db.execute(stmt)

                    account = ibm_db.fetch_assoc(stmt)

                    if account:
                        # the mail entered by the agent is in the database

                        # checking if the customer entered a valid password now
                        # encrypting the entered password
                        passcode = str(hashlib.sha256(password.encode()).hexdigest())

                        # now checking if this passcode is equal to that of the password in database
                        if(account['PASSCODE'] == passcode):
                            # valid password
                            msg = "Valid Login"
                            to_show = True

                            # initialising the agent object
                            agent.set(
                                account['AGENT_ID'],
                                account['FIRST_NAME'],
                                account['LAST_NAME'],
                                account['EMAIL'],
                                account['PASSCODE'],
                                account['DATE_JOINED'],
                                account['CONFIRMED']
                            )

                            session.permanent = False
                            session['LOGGED_IN_AS'] = "AGENT"
                            login_user(agent, remember=True)

                            if agent.confirm:
                                print("summa")

                            else:
                                # the agent is not yet verified by the admin
                                # re-directing the agent to the agent no show page
                                return redirect(url_for('agent.no_show'))

                        else:
                            # invalid password
                            msg = "Invalid password"
                            password = ""
                            to_show = True

                    else:
                        # invalid agent 
                        # i.e, entered mail is not present in the database
                        msg = "Agent does not exist"
                        email = ""
                        password = ""
                        to_show = True

        return render_template(
            'login.html',
            to_show = to_show,
            message = msg,
            email = email,
            password = password
        )

    return render_template('login.html')

@views.route('/register', methods = ['GET', 'POST'])
def register():
    # if method is POST
    if request.method == 'POST':
        # getting all the data entered by the user
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        role = request.form.get('role-check')

        msg = ""
        to_show = False

        # validating the inputs 
        if len(first_name) < 3:
            msg = "First Name must be atleast 3 characters long!"
            to_show = True

        elif len(last_name) < 1:
            msg = "Last Name must be atleast 1 characters long!"
            to_show = True

        elif(not (re.fullmatch(email_regex, email))):
            msg = "Please enter valid email"
            to_show = True

        elif((len(password) < 8) or (len(confirm_password) < 8)):
            msg = "Password must be atleast 8 characters long!"
            to_show = True

        elif (password != confirm_password):
            msg = "Passwords do not match"
            to_show = True

        elif (not (re.fullmatch(pass_regex, password))):
            msg = "Enter valid password"
            to_show = True

        if to_show:
            # there is something fishy with the inputs
            password = confirm_password = ""

        # by here the inputs are validated, because to_show is False
        # registering the user / agent with the database
        elif (not to_show):
            if role == "Customer":
                # the user is a Customer
                # checking whether the user with the same email already there
                check_mail_query = "SELECT * FROM customer WHERE email = ?"
                stmt = ibm_db.prepare(conn, check_mail_query)
                ibm_db.bind_param(stmt, 1, email)
                ibm_db.execute(stmt)

                account = ibm_db.fetch_assoc(stmt)

                if account:
                    # user already exists
                    msg = "Email already exists!"
                    email = ""
                    password = ""
                    confirm_password = ""
                    to_show = True

                else:
                    # new customer
                    # adding the customer details to the detabase

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/agent dashboard.html
{% extends 'dashboard.html' %}

{% block left %}
{% endblock %}

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="../static/images/cart logo white-modified.png">
    
    <!-- Linking css, js, Google fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}"/>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <script src="{{ url_for('static', filename='js/pass.js') }}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Linking Watson Assistant -->
    {% block watson %}
    {% endblock %}
</head>
<body>
    {% block alert %}
        {% if to_show %}
            <script>
                alert('{{ message }}')
            </script>
        {% endif %}
    {% endblock %}

    {% block main %}
    {% endblock %}
</body>
</html>

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/cust change.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Change Password
{% endblock %}

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/cust support.html
{% extends 'cust dashboard.html' %}

{% block title %}
    Support
{% endblock %}

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/cust tickets.html
{% extends 'cust dashboard.html' %}

{% block title %}
    All tickets
{% endblock %}

{% block right %}
    <div class="profile-div">
        <h1>Tickets raised by you!</h1>
        <div class="new-t-div">
            {% if tickets_to_show %}
                <p>{{ msg }}</p>

                <table class="agents-table">
                    <tr>
                        <th class="agents-table-heading">TICKET ID</th>
                        <th class="agents-table-heading">DATE</th>
                        <th class="agents-table-heading">STATUS</th>
                        <th class="agents-table-heading">QUERY</th>
                        <th class="agents-table-heading">AGENT</th>
                        <th class="agents-table-heading">ADDRESS <br/> COLUMN</th>
                    </tr>
                    {% for ticket in tickets %}
                        <tr>
                            <td class="agents-table-element">{{ ticket[0][0:5] }}</td>
                            <td class="agents-table-element">{{ ticket[1] }}</td>
                            <td class="agents-table-element">
                                <div class="open-ticket">
                                    {{ ticket[2] }}
                                </div>
                            </td>
                            <td class="agents-table-element">
                                <button onclick="showTicket('{{ ticket[3] }}')" class="view-query">View</button>
                            </td>
                            <td class="agents-table-element">
                                {% if ticket[4] %}
                                    {{ ticket[4] }}
                                {% else %}
                                    <p>N/A</p>
                                {% endif %}
                            </td>
                            <td class="agents-table-element">
                                {% if ticket[2] == "OPEN" %}
                                    <p>-</p>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            {% else %}
                <p>{{ msg }}</p>
            {% endif %}
        </div>
    </div>

    <script>
        /* Function to show the query of the ticket */
        function showTicket(ticket){
            alert(ticket)
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/dashboard.html
{% extends 'base.html' %}

{% block main %}
    <div class="dashboard-div">
        <nav>
            <div class="dash-nav">
                <div>
                    <div class="dash-img-text">
                        <img src="../static/images/cart logo white-modified.png" class="img-in-nav" alt="logo"/>
                        <h3>Customer Care Registry</h3>
                    </div>
                </div>
                <div>
                    <div class="online-div" onclick="showSettings()">
                        <img src="../static/images/cust profile.png" class="img-in-nav" alt="logo"/>
                    </div>
                </div>
            </div>
        </nav>
        
        <div class="dash-body">
            <div class="dash-left">
                {% block left %}
                {% endblock %}
            </div>
            <div class="dash-right">
                {% block right %}
                {% endblock %}
            </div>
        </div>

        <div class="settings-menu" id="settings-menu" style="visibility: hidden;">
            <div>
                <p>Want to Logout?</p>
                <a href="{{ url_for('blue_print.logout') }}">
                    <button class="logout-btn" type="button">Logout</button>
                </a>
            </div>
        </div>
    </div>

    <script>
        function showSettings(){
            var settings = document.getElementById("settings-menu");

            settings.style.visibility = settings.style.visibility == "hidden" ? "visible" : "hidden";
        }
    </script>
{% endblock %}

Project Development Phase/Sprint 2/Customer Care Registry/registry/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block main %}
    <section class="login-section">
        <div class="login-div">
            <div class="login-header">
                <img src="{{ url_for('static', filename='images/cart logo white.png') }}" class="login-img" alt="logo" />
                <h2>Sign in</h2>
                <p>Use your Registry Account</p>
            </div>
            <div class="login-remind">
                <form action="{{ url_for('blue_print.login') }}" method="POST" class="login-form">
                    <label>Email</label>
                    <input type="email" required value="{{ email }}" name="email" placeholder="Enter your email"/>
                    
                    <label>Password</label>
                    <input type="password" required value="{{ password }}" name="password" id="password-input" placeholder="Enter your email"/>

                    <div class="show-pass-div">
                        <input type="checkbox" onclick="showPassword()" style="height: 20px;"/>
                        <p>Show Password</p>
                    </div>

                    <div class="role-div">
                        <p>Role : </p>
                        <div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Customer" checked name="role-check"/>
                                <p>Customer</p>
                            </div>
                            <div>
                                <input type="radio" style="height: 20px;" value="Agent" name="role-check"/>
                                <p>Agent</p>
                            </div>
                        </div>
                    </div>

                    <button class="submit-btn" type="submit">Login</button>

                    <div>
                        <a href="#" class="links">Forgot Password?</a> <br> 
                        <div>
                            <a href="{{ url_for('blue_print.register') }}" class="links">Don't have an account yet? Register</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}